export enum APP_CONSTANTS {
  LOAD_MOVIES_LIST = 'LOAD_MOVIES_LIST',
  UPDATE_MOVIES_LIST = 'UPDATE_MOVIES_LIST',
  UPDATE_SEARCH_CRITERIA = 'UPDATE_SEARCH_CRITERIA',
  LOAD_MOVIES_DETAILS_BY_ID = 'LOAD_MOVIES_DETAILS_BY_ID',
  UPDATE_MOVIE_DETAILS='UPDATE_MOVIE_DETAILS'
}
